package com.dto;

import java.sql.Date;
import java.sql.Timestamp;

public class MediaDTO extends AuthDTO {
    public String mediaId;
    public String fileName;
    public String fileType;
    public String musicPrefId;
    public String uploader;
    public String tags;
    public String path;
    public String isAd;
    public String skipFlag;
    public String location;
    public String privilege;
    public String latitude;
    public String longitude;
    public String artist;
    public String thumbnail;
    public String description;
    public String artistId;
    public String albumId;
    public String mediaLength;
    public String rank;
    public String title;
    public String songTitle;
    public String edlFilePath;
    public String metadataFilePath;
    public String isSkit;
    public Date mediaDate;
    public String stationList;
    public String isFeatured;
    public String projectName;
    public String postType;
    public Boolean likeFlag;
    public String postedAs;
    public String postedId;
    public Timestamp scheduledStartTime;
    public Timestamp scheduledEndTime;
    public String isScheduled;
    public String flag;
    public String flaggedBy;
    public String flaggedReason;
    public Timestamp createdDate;
    public String seriesId;
    public String episodeNumber;
    public String urlId;
}
